batch_size: 8
iters: 8000

train_dataset:
  type: Dataset
  dataset_root: custom_dataset/v16-a
  train_path: custom_dataset/v16-a/train_list.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [512, 1280]
    - type: Normalize
  mode: train

val_dataset:
  type: Dataset
  dataset_root: custom_dataset/v16-a
  val_path: custom_dataset/v16-a/val_list.txt
  num_classes: 2
  transforms:
    - type: Resize
      target_size: [512, 1280]
    - type: Normalize
  mode: val

optimizer:
  type: sgd
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: MixedLoss
      losses:
        - type: CrossEntropyLoss
        - type: DiceLoss
      coef: [0.7, 0.3]
  coef: [1, 1, 1]

model:
  type: PPLiteSeg
  backbone:
    type: STDC2
    pretrained: https://bj.bcebos.com/paddleseg/dygraph/PP_STDCNet2.tar.gz

